[DAG]
schedule = "@continuous"
type = "rdbms-to-dwh"

[Extract]
conn_id = "transactions_default"
database_name = "database"
table_name = "table"
type = "postgres"

[Load]
conn_id = "transactions_dwh_default"
database_name = "database"
table_name = "table"
type = "redshift"
